### ISSUE TITLE
Add compatibility

### ISSUE THREAD

**Issue by EvilKilem** [DAQEM/JobsPlus-Archive#57] opened 2022-12-11 16:02 UTC
Any way to add compatibility with curios, would be nice if i could put the builders backpacks in the back slot.  Thanks for your hard work.

**Comment by DAQEM** [comment] 2022-12-11 16:45
Duplicate of #4. I'm not going to do this because I'm very busy with other features, I'm sorry. If people want, they van create a fork and pull request to add it.

**Closed as not planned by DAQEM** 2022-12-11 16:45 UTC
